# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=30)),
                ('date', models.DateTimeField()),
                ('picture', models.ImageField(upload_to='post/post_picture/')),
                ('text', models.TextField()),
                ('display', models.BooleanField(default=True)),
                ('likes', models.IntegerField()),
                ('dislikes', models.IntegerField()),
            ],
        ),
    ]
