# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 12:59
from __future__ import unicode_literals

from django.db import migrations, models
import redactor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20160713_1423'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date'], 'verbose_name': '\u043f\u043e\u0441\u0442', 'verbose_name_plural': '\u043f\u043e\u0441\u0442\u044b'},
        ),
        migrations.AlterField(
            model_name='post',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=redactor.fields.RedactorField(max_length=255),
        ),
    ]
